sudo: false
language: node_js
node_js:
  - "10"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - if [[ $(uname -s) == 'Linux' ]]; then
      export CXXFLAGS="-stdlib=libc++";
    fi;
install:
  - npm i
