sudo: false
language: node_js
node_js:
  - "10"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - clang-3.5
before_install:
  - if [[ $(uname -s) == 'Linux' ]]; then
    export CXX="clang++-3.5";
    export CC="clang-3.5";
    fi;
  - export PATH=./node_modules/.bin/:$PATH
  - npm install node-gyp -g
install:
  - npm i
